import { v4 as uuidv4 } from "uuid";

export const recommendFastFood = [
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/samyangtomatopasta-598x598.webp"),
    dopPhoto: require("./imgs/ramen/SamyangKimchiBuldakHotChickenInstantNoodles2.webp"),
    name: 'Рамен SamYang Buldak "Острая курица с томатным соусом"',
    price: "158грн",
    Defprice: "158грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Очередная версия знаменитой серии Buldak Hot Chicken Ramen — рамен с томатной пастой.Это простое в приготовлении блюдо обладает вкусом острого соуса пультак в сочетании с томатной пастой и идеально подходит для быстрого обеда или ужина.  Соус готовится из настоящих помидоров и смеси пикантных специй, что придает ему насыщенный и сытный вкус, который обязательно удовлетворит вашу тягу к острому.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/carbonara-598x598.webp"),
    dopPhoto: require("./imgs/ramen/OIP (8).jpg"),
    name: 'Рамен SamYang Buldak "Острая курица с соусом Карбонара"',
    Defprice: "158грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Острая лапша со вкусом курицы в соусе карбонара от Samyang - идеальный выбор для тех, кто ценит оригинальные и пикантные блюда. Этот продукт не только подарит вам наслаждение благодаря своему уникальному сочетанию остроты и кремовой текстуры, но и поможет поддерживать высокую работоспособность в течение дня. Соус карбонара, приготовленный с использованием лучших ингредиентов, придает лапше насыщенный и богатый вкус, который обязательно понравится гурманам и любителям азиатской кухни.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/4393022258_w640_h640_ramen-samyang-ostraya.webp"),
    dopPhoto: require("./imgs/ramen/BADE4B5B-DDBF-4A74-AB67-100DDAD14B07-700x700.webp"),
    name: 'Рамен Samyang Buldak "Острая курица и Сыр"',
    price: "150грн",
    Defprice: "150грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Любимый Buldak от Samyang с изысканным сырным вкусом. Это блюдо точно разнообразит жизнь любителей острой еды. Приготовленная из высококачественных ингредиентов, эта лапша не только обладает великолепным вкусом, но и производится в соответствии с строгими стандартами здоровья, что гарантирует её качество.",
    shelfLife: "1 год",
  },

  {
    id: uuidv4(),
    photo: require("./imgs/ramen/245689747.webp"),
    dopPhoto: require("./imgs/ramen/16589445721_1262681431.jpg"),
    name: "Рамен Ottogi с сыром и специями",
    price: "109грн",
    Defprice: "109грн",
    weight: "111г",
    type: "Лапша",
    producer: "Ottogi",
    data: "Ottogi вновь очаровывает своей продукцией. Лапша со вкусом сыра и различными специями подарит незабываемые ощущения и сытость на долгое время. Блюдо простое в приготовлении и не займет у вас много времени. Просто залейте кипятком на 5 минут и наслаждайтесь.",
    shelfLife: "1 год",
  },

  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yopokkicheese-598x598.webp"),
    dopPhoto: require("./imgs/ramen/Yopokki-Tteokbokki-Cheese-Cup-EU-1080-5.webp"),
    name: "Сырные Токпокки Yopokki",
    price: "160грн",
    Defprice: "160грн",
    weight: "120г",
    producer: "Yopokki",
    data: "Острый и пикантный сырный соус безупречно дополняет рисовые палочки, превращая каждую порцию в настоящее удовольствие. Позиция предназначена для приготовления в микроволновой печи - блюдо готовится всего за несколько минут, так что вы можете наслаждаться настоящей корейской кухней в уюте собственного дома.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yopokkigarlicteriyaki-598x598.webp"),
    dopPhoto: require("./imgs/ramen/yopokkigarlicteriyaki1-700x700.webp"),
    name: "Чесночные Токпокки Yopokki",
    price: "160грн",
    Defprice: "160грн",
    weight: "120г",
    producer: "Yopokki",
    data: "Аппетитное сочетание ароматного чеснока и сладко-острого соуса терияки, которое добавляет уникальный оттенок классическим токпокки. Позиция предназначена для приготовления в микроволновой печи - блюдо готовится всего за несколько минут, так что вы можете наслаждаться настоящей корейской кухней в уюте собственного дома.",
    shelfLife: "1 год",
  },
];

export const recomendedSauces = [
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/carbonarasauce11-598x598.webp"),
    dopPhoto: require("./imgs/sauces/carbonarasauce1-700x700.webp"),
    name: "Острый соус Samyang Buldak Carbonara",
    price: "278грн",
    Defprice: "278грн",
    weight: "200г",
    producer: "SamYang",
    data: "Идеальное сочетание остроты и мягкости сливок, которое создаёт уникальный вкус. Подойдет к лапше, суши и мясу",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/samyangkrazytigercorianderlime-598x598.webp"),
    dopPhoto: require("./imgs/sauces/samyangkrazytigercorianderlime2-700x700.webp"),
    name: "Соус Krazy Tiger Exotic Spice Coriander&Lime Chili Crisp Sauce Samyang",
    price: "340грн",
    Defprice: "340грн",
    weight: "175г",
    producer: "SamYang",
    data: "Соус Krazy Tiger Exotic Spice Coriander&Lime - это уникальное сочетание корейского перца чили, кинзы, лайма и рыбного соуса. Он прекрасно подходит для морепродуктов, жареных блюд и может использоваться в качестве маринада для придания пикантности и аромата. Добавьте его в свои блюда, чтобы подчеркнуть вкус и сделать их более экзотическими.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/samyangkrazytigerredchili-598x598.webp"),
    dopPhoto: require("./imgs/sauces/samyangkrazytigerredchili1-700x700.webp"),
    name: "Соус Krazy Tiger Korean Spice Red Chili Crisp Sauce Samyang",
    price: "340грн",
    Defprice: "340грн",
    weight: "175г",
    producer: "SamYang",
    data: "Соус Krazy Tiger Korean Spice объединяет в себе огненную смесь любимого соуса Buldak, чили и чеснока, вдохновлённую смелыми вкусами корейской кухни. Его насыщенный вкус придаст вашим блюдам неповторимую пикантность и остроту, идеально сочетаясь с мясом, овощами или даже как заправка для лапши.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/ottogihoneymustard-598x598.webp"),
    dopPhoto: require("./imgs/sauces/honeiSauces.webp"),
    name: "Соус Honey Mustard Ottogi",
    price: "218грн",
    Defprice: "218грн",
    weight: "265г",
    producer: "Ottogi",
    data: "В этом соусе Ottogi гармонично сочетаются сладость меда и пикантная кислинка горчицы. Он обладает нежным и чистым послевкусием, поэтому его можно использовать в различных блюдах, таких как салаты, жареные блюда, а также блюда с курицей. В составе соуса есть акациевый мед (6%) и горчица (17,19%).",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/zhongjingscallionsauce-598x598.webp"),
    dopPhoto: require("./imgs/sauces/HanhaOnion.jpg"),
    name: "Соус с олией шанхайского лука Zhongjing",
    price: "30грн",
    Defprice: "30грн",
    weight: "30г",
    data: "Соус с маслом шанхайского лука от известного китайского бренда Zhongjing обладает насыщенным вкусом и ароматом свежего лука и отлично дополнит вашу любимую лапшу.",
    shelfLife: "18 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/tigerbanggarlicsauce-598x598.webp"),
    dopPhoto: require("./imgs/sauces/tigerbanggarlicsauce1-700x700.webp"),
    name: "Острый соус с чесноком Ying Chao Tiger Bang",
    price: "278грн",
    Defprice: "278грн",
    weight: "210г",
    data: "Сладко-острый китайский соус чили с добавлением измельченного чеснока.Этот соус отлично подходит в качестве приправы, заправки для салатов, добавки к лапше и жареному рису, а также к холодным блюдам и соусам.",
    shelfLife: "1 год",
  },
];

export const recomendedSweets = [
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/mochistrawberryyukilove-598x598.webp"),
    dopPhoto: require("./imgs/sweets/mochistrawberryyukilove2-700x700.webp"),
    name: "Moти Strawberry Yuki & Love",
    price: "175грн",
    Defprice: "175грн",
    weight: "180г",
    data: "Нежный десерт из клейкого рисового теста с сладким и мягким вкусом клубники. Моти дайфуку прекрасно подходит в качестве угощения к чашечке любимого кофе или чаю. В упаковке 12 пирожных, каждое в индивидуальной упаковке.",
    shelfLife: "1 год",
  },

  {
    id: uuidv4(),
    photo: require("./imgs/sweets/OIP.jpg"),
    dopPhoto: require("./imgs/sweets/lottemilkcandy1-700x700.webp"),
    name: "Конфеты с молочным вкусом Lotte",
    price: "92грн",
    Defprice: "92грн",
    weight: "63г",
    data: "Корейские конфеты с ярким молочным вкусом от Lotte, которые непременно понравятся любителям азиатских сладостей. Сочетание легкой кислинки и сгущенного молока образует неповторимый вкус.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/lottestrawberrycandy-598x598.webp"),
    dopPhoto: require("./imgs/sweets/lottestrawberrycandy1-700x700.webp"),
    name: "Конфеты со вкусом молочной клубники Lotte",
    price: "96грн",
    Defprice: "96грн",
    weight: "63г",
    data: "Корейские конфеты от Lotte с насыщенным вкусом молока и клубники имеют легкую кислинку, которая обязательно понравится любителям корейских сладостей. Сочетание свежей клубники и сгущенного молока дарует неповторимый вкус.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/OIP (4).jpg"),
    dopPhoto: require("./imgs/sweets/il_fullxfull.5309357587_eljp.jpg"),
    name: "Поки Lotte Pepero Snowy Almond",
    price: "78грн",
    Defprice: "78грн",
    weight: "32г",
    data: "Печенье Lotte Pepero — это популярное сладкое угощение из Южной Кореи. Оно представляет собой палочку печенья, покрытую белым шоколадом и измельченными орехами, что придает сладкий и хрустящий вкус. Эта закуска завоевала популярность не только в Южной Корее, но и по всему миру, став любимым лакомством для тех, кто ценит сочетание кремовой и хрустящей текстур в удобном формате палочек.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/SC0061-s2.jpg"),
    dopPhoto: require("./imgs/sweets/54339791.jpg"),
    name: "Поки Lotte Pepero Almond",
    price: "78грн",
    Defprice: "78грн",
    weight: "32г",
    data: "Печенье Lotte Pepero — это известное сладкое угощение из Южной Кореи. Оно представляет собой палочку печенья, покрытую молочным шоколадом и измельченными орехами, что придает ей сладкий и хрустящий вкус. Эта закуска завоевала популярность не только в Южной Корее, но и в других странах, став любимым лакомством для тех, кто ценит сочетание кремовой и хрустящей текстур в удобном формате палочек. Вкуснейший десерт с воздушной кремово-клубничной начинкой, покрытый белым шоколадом, не оставит вас равнодушным. Идеальное сочетание текстуры и вкуса подарит вам незабываемые ощущения.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/OIP (5).jpg"),
    dopPhoto: require("./imgs/sweets/PockyAlmondCrush2_2048x2048.webp"),
    name: "Поки Almond Crush",
    price: "78грн",
    Defprice: "78грн",
    weight: "32г",
    data: "Этот роскошный вариант Pocky включает хрустящие бисквитные палочки, покрытые густым молочным шоколадом и щедро посыпанные дроблеными миндалем. Они имеют отличную текстуру, а сочетание миндаля и кремового шоколада создаёт восхитительный, насыщенный вкус.",
    shelfLife: "1 год",
  },
];

export const recomendedChips = [
  {
    id: uuidv4(),
    photo: require("./imgs/chips/orionkkobukspicycornchips-598x598.webp"),
    dopPhoto: require("./imgs/chips/orionkkobukspicycornchips11-700x700.webp"),
    name: "Острые снеки Kkobuk Chips Orion",
    price: "92грн",
    Defprice: "92грн",
    type: "Снеки",
    weight: "80г",
    data: "Острые кукурузные снеки, известные как «четырёхслойные снеки», от всемирно известного бренда Orion. Каждый кусочек имеет непревзойдённый пикантный вкус и станет отличным дополнением во время просмотра любимых дорам. Также эти снеки часто добавляют в супы, что насыщает их более интересным и богатым вкусом.",
    shelfLife: "5 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/samyangchanggusnack-598x598.webp"),
    dopPhoto: require("./imgs/chips/samyangchanggusnack2-700x700.webp"),
    name: "Снеки Ottogi Ppushu Ppushu Noodle Snack",
    price: "198грн",
    Defprice: "198грн",
    type: "Снеки",
    weight: "115г",
    producer: "Ottogi",
    data: "Очень сладкие и совсем не острые хрустящие снеки с медовым вкусом и кунжутными семечками от Samyang. Производитель советует употреблять их с мороженым или молоком.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/bibizancrackers-598x598.webp"),
    dopPhoto: require("./imgs/chips/bibizancrackers1-700x700.webp"),
    name: "Рисовые крекеры Bibizan",
    price: "94грн",
    Defprice: "94грн",
    type: "Снеки",
    weight: "128г",
    data: "Хрустящие рисовые крекеры с сычуаньским перцем. Выбирай уровень остроты по своему вкусу и наслаждайся крекерами от Bibizan. Они идеально сочетаются с вашим любимым напитком.",
    shelfLife: "8 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/likedorosesnack-598x598.webp"),
    dopPhoto: require("./imgs/chips/likedorosesnack2-700x700.webp"),
    name: "Снеки Rosé Tteokbokki LikeDo",
    price: "122грн",
    Defprice: "122грн",
    type: "Снеки",
    weight: "83г",
    data: "Вершково-томатный соус K-Rosé обладает мягкой пикантностью и идеально подходит тем, кто предпочитает нежную остроту. Комбинация острого перца и сливок придает закускам Rosé Tteokbokki более мягкий вкус, который, безусловно, придётся по вкусу.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/ghostpepper-598x598.webp"),
    dopPhoto: require("./imgs/chips/Mister-Potato-Ghost-Pepper-Black-Crisps-Review-5.jpg"),
    name: "Острые чипсы Ghost Pepper Mamee",
    price: "118грн",
    Defprice: "118грн",
    type: "Чипсы",
    weight: "45г",
    data: "Рамен-снек от известного бренда Ottogi. Очень острый и хрустящий. Вам не нужно кипятить воду, чтобы насладиться любимым вкусом, так как эту лапшу можно есть прямо из пакетика, предварительно раздробив её и посыпав приправой. Снеки идеально подходят для перекусов в пути, вечеринок или просто для того, чтобы утолить желание острого в любое время.",
    shelfLife: "18 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/haitaihoneychips-598x598.webp"),
    dopPhoto: require("./imgs/chips/haitaihoneychips1-700x700.webp"),
    name: "Чипсы Honey Butter Chips Haitai Calbee",
    price: "92грн",
    Defprice: "92грн",
    type: "Чипсы",
    weight: "60г",
    data: "Корейские чипсы из батата с вкусом масла и меда от компаний Haitai и Calbee. Эти чипсы отличаются гармоничным сочетанием сладкого и соленого, поскольку Haitai — настоящий эксперт в производстве закусок и снеков.",
    shelfLife: "9 месяцев",
  },
];

export const recommendProducts = [
  ...recommendFastFood,
  ...recomendedSauces,
  ...recomendedSweets,
  ...recomendedChips,
];

export const noodleInformation = [
  {
    text: "Лапша – это популярное блюдо, известное во многих культурах по всему миру. Она представляет собой тонкие полоски теста, приготовленные из муки, воды, в некоторых случаях добавляют яйца. Существует множество видов лапши, отличающихся по составу, способу приготовления и форме. В нашем ассортименте есть: гречневая лапша соба, пшеничный удон, рисовая лапша.",
    img: require("./imgs/icons/ramen.png"),
  },
];

export const noodles = [
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/samyangtomatopasta-598x598.webp"),
    dopPhoto: require("./imgs/ramen/SamyangKimchiBuldakHotChickenInstantNoodles2.webp"),
    name: 'Рамен SamYang Buldak "Острая курица с томатным соусом"',
    price: "158грн",
    Defprice: "158грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Очередная версия знаменитой серии Buldak Hot Chicken Ramen — рамен с томатной пастой.Это простое в приготовлении блюдо обладает вкусом острого соуса пультак в сочетании с томатной пастой и идеально подходит для быстрого обеда или ужина.  Соус готовится из настоящих помидоров и смеси пикантных специй, что придает ему насыщенный и сытный вкус, который обязательно удовлетворит вашу тягу к острому.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/carbonara-598x598.webp"),
    dopPhoto: require("./imgs/ramen/OIP (8).jpg"),
    name: 'Рамен SamYang Buldak "Острая курица с соусом Карбонара"',
    price: "158грн",
    Defprice: "158грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Острая лапша со вкусом курицы в соусе карбонара от Samyang - идеальный выбор для тех, кто ценит оригинальные и пикантные блюда. Этот продукт не только подарит вам наслаждение благодаря своему уникальному сочетанию остроты и кремовой текстуры, но и поможет поддерживать высокую работоспособность в течение дня. Соус карбонара, приготовленный с использованием лучших ингредиентов, придает лапше насыщенный и богатый вкус, который обязательно понравится гурманам и любителям азиатской кухни.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/nongcheesekimchi-598x598.webp"),
    dopPhoto: require("./imgs/ramen/nongkimchicheese123-700x700.webp"),
    name: "Суп Kimchi Cheese Ramyun Nongshim",
    price: "85грн",
    Defprice: "85грн",
    weight: "120г",
    type: "Суп",
    producer: "Nongshim",
    data: "Благодаря уникальному сочетанию кисло-острого вкуса кимчи с вкусом сыра и качественной упругой лапши рамен, готовое блюдо обладает пикантным ароматом, суп получается густым, вкусным и непременно подарит вам новое вкусовое удовольствие.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/nongshimshrimpflavor-598x598.webp"),
    dopPhoto: require("./imgs/ramen/nongshimshrimp1111-700x700.webp"),
    name: "Суп Shin Ramyun Nongshim со вкусом креветок",
    price: "86грн",
    Defprice: "86грн",
    weight: "120г",
    type: "Суп",
    producer: "Nongshim",
    data: "Классический Shin Ramyun теперь также со вкусом креветок! Невероятно острый и прозрачный суп со вкусом креветок и упругой лапшой, приготовленной из лучших ингредиентов, точно не оставит вас равнодушными. Приготовление занимает всего несколько минут, и вот вы уже наслаждаетесь ароматным и насыщенным бульоном по традиционному корейскому рецепту.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/4393022258_w640_h640_ramen-samyang-ostraya.webp"),
    dopPhoto: require("./imgs/ramen/BADE4B5B-DDBF-4A74-AB67-100DDAD14B07-700x700.webp"),
    name: 'Рамен Samyang Buldak "Острая курица и Сыр"',
    price: "150грн",
    Defprice: "150грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Любимый Buldak от Samyang с изысканным сырным вкусом. Это блюдо точно разнообразит жизнь любителей острой еды. Приготовленная из высококачественных ингредиентов, эта лапша не только обладает великолепным вкусом, но и производится в соответствии с строгими стандартами здоровья, что гарантирует её качество.",
    shelfLife: "1 год",
  },

  {
    id: uuidv4(),
    photo: require("./imgs/ramen/245689747.webp"),
    dopPhoto: require("./imgs/ramen/16589445721_1262681431.jpg"),
    name: "Рамен Ottogi с сыром и специями",
    price: "109грн",
    Defprice: "109грн",
    weight: "111г",
    type: "Лапша",
    producer: "Ottogi",
    data: "Ottogi вновь очаровывает своей продукцией. Лапша со вкусом сыра и различными специями подарит незабываемые ощущения и сытость на долгое время. Блюдо простое в приготовлении и не займет у вас много времени. Просто залейте кипятком на 5 минут и наслаждайтесь.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/4358416563_w640_h640_ramen-buldak-ostraya.webp"),
    dopPhoto: require("./imgs/ramen/ramen-buldak02_1024x1024.webp"),
    name: 'Рамен SamYang Buldak "Острая Курица"',
    price: "98грн",
    Defprice: "98грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Острая корейская лапша со вкусом курицы Buldak Samyang - идеальный выбор для любителей необычных, жгучих и сытных блюд азиатской кухни.Эта лапша утолит голод, придаст новые силы для работы и подарит хорошие впечатление. Пшеничная лапша - один из главных компонентов корейской кухни, и её можно встретить в самых разных формах. Всего за 5 минут вы приготовите полноценный обед, который обязательно захочется повторить.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yumjapanesechicken-598x598.png"),
    dopPhoto: require("./imgs/ramen/yumyumjapchicken-700x700.jpg"),
    name: 'Суп YumYum со вкусом "Курица по-японски"',
    price: "50грн",
    Defprice: "50грн",
    weight: "60г",
    type: "Суп",
    producer: "YumYum",
    data: "Почувствуйте вкус настоящей азиатской кухни, в которой сочетаются отборные ингредиенты, воссоздающие уникальный характер вкуса японской курицы с соевым соусом шою, усиленный имбирем, куркумой и водорослями вакаме.Благодаря изысканному сочетанию эластичной упругой лапши и насыщенного супа, вы получите настоящее наслаждение, потратив на приготовление всего несколько минут.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/duck-flavour-600x600.jpg"),
    name: 'Суп YumYum со вкусом "Утки Юмюм"',
    price: "50рн",
    Defprice: "50рн",
    weight: "60г",
    type: "Суп",
    producer: "YumYum",
    data: "Суп с насыщеным вкусом утки Юмюм и вкуснейшими специями такими как чеснок и лук не оставят вас равнодушными. Эта лапша с супом насытит Вас и порадует своим вкусом.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yumcurry-598x598.webp"),
    dopPhoto: require("./imgs/ramen/dc04df_676727294d174a29858ca73b08457ccf~mv2.webp"),
    name: 'Суп YumYum со вкусом "Зеленый кари"',
    price: "50рн",
    Defprice: "50рн",
    weight: "60г",
    type: "Суп",
    producer: "YumYum",
    data: "Лапша быстрого приготовления YumYum со вкусом одного из культовых тайских блюд — зеленого карри. Это чрезвычайно ароматное, пряно-кислое блюдо с освежающим вкусом и нотками умами, благодаря добавлению рыбного соуса.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/2475318326_w640_h640_lapsha-bystrogo-prigotovleniya.webp"),
    name: "Лапша Удон Samyang",
    price: "80грн",
    Defprice: "80грн",
    weight: "100г",
    type: "Лапша",
    producer: "SamYang",
    data: " U-DONG SamYang - корейское блюдо быстрого приготовления, очень вкусное, острое и ароматное. Изготавливается из пшеничной муки с добавлением традиционных корейских специй. Прекрасно подходит для обеда на рабочем месте и во время путешествий. Быстро насыщает и гарантирует высокую работоспособность на весь день, а ее соблазнительный аромат поднимает настроение и улучшает аппетит. Ее нужно залить 500 мл воды и варить 4 мин.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/ottogimildcup-598x598.webp"),
    dopPhoto: require("./imgs/ramen/ottogimildcup1-700x700.webp"),
    name: "Суп Jin Ramen (Mild) Ottogi в стакане",
    price: "90грн",
    Defprice: "90грн",
    type: "Суп",
    weight: "65г",
    producer: "Ottogi",
    data: "Лапша Jin Ramen (Mild) от торговой марки Ottogi - это отличная возможность вкусно пообедать без лишних затрат времени и денег. Она отличается приятным вкусом с легкой остротой и хорошо утоляет голод, обеспечивая организм энергией. А насыщенный говяжий бульон с приятными грибными нотками не оставит вас равнодушными.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/samyangrosecreambigbowl-598x598.webp"),
    dopPhoto: require("./imgs/ramen/samyangrosecreambigbowl1-700x700.webp"),
    name: 'Рамен Samyang Buldak "Rosé Cream" Big Bowl',
    price: "128грн",
    Defprice: "128грн",
    weight: "105г",
    type: "Лапша",
    producer: "SamYang",
    data: "Ощутите насыщенный вкус, не похожий ни на один другой, с почти сладким и кремовым вкусом K-Rosé соуса, который заставит вас хотеть еще больше. Идеальное сочетание любимого соуса пультак, острого перца и нежных сливок, которое определенно стоит попробовать. Благодаря уровню остроты 2 из 5 уровней BFL (Buldak Fire Level), этой лапшой могут наслаждаться даже те, кто предпочитает менее пикантные вкусы.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/spicycheeseramen-598x598.webp"),
    dopPhoto: require("./imgs/ramen/spicy-cheese1-700x700.webp"),
    name: 'Суп рамен "Острый сыр" Ottogi',
    price: "105грн",
    Defprice: "105грн",
    weight: "111г",
    type: "Суп",
    producer: "Ottogi",
    data: "Сыр - один из тех ингредиентов, которые хорошо сочетаются с лапшой быстрого приготовления. Непревзойденное сочетание пикантного сырного супа и корейской лапши рамён, наполненное специями и классической смесью качественных овощей. Сливочный сыр добавляет глубины вкусу острому бульону рамена, делая его гораздо ароматнее, вкуснее и приятнее! Если вы любите сыр, вам точно понравится корейский острый рамен с сыром от бренда Ottogi.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/samyangsweetspicychicken-598x598.webp"),
    dopPhoto: require("./imgs/ramen/samyangsweetspicychicken11-700x700.webp"),
    name: "Лапша Рамен Buldak Sweet & Spicy Sanyang",
    price: "128грн",
    Defprice: "128грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Качественная лапша Samyang, насыщенный и ароматный сладко-острый соус Buldak с вкусом жареной курицы, сочетание белого и черного обжаренного кунжута — все это создает потрясающий аутентичный вкус, а уровень остроты 3/5 BFL (Buldak Fire Level) добавляет приятную пикантность.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/nongshimshrimpflavor-598x598.webp"),
    dopPhoto: require("./imgs/ramen/nongshimshrimp1111-700x700.webp"),
    name: "Суп Shin Ramyun Nongshim со вкусом креветок",
    price: "86грн",
    Defprice: "86грн",
    weight: "120г",
    type: "Суп",
    producer: "Nongshim",
    data: "Классический Shin Ramyun теперь также со вкусом креветок! Невероятно острый и прозрачный суп со вкусом креветок и упругой лапшой, приготовленной из лучших ингредиентов, точно не оставит вас равнодушными. Приготовление занимает всего несколько минут, и вот вы уже наслаждаетесь ароматным и насыщенным бульоном по традиционному корейскому рецепту.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/ottogijinjjambbongcup-598x598.webp"),
    dopPhoto: require("./imgs/ramen/ottogijinjjambbongcup1-700x700.webp"),
    name: "Суп рамен Jin Jjambbong Spicy Ramen Ottogi в стакане",
    price: "98грн",
    Defprice: "98грн",
    weight: "75г",
    type: "Суп",
    producer: "Ottogi",
    data: "Острый суп-лапша со вкусом морепродуктов Jin Jjambbong Spicy Ramen от Ottogi обязательно вас удивит. Специальная смесь морепродуктов придает насыщенность и глубину и без того ароматному бульону. Если вы ищете легкую еду для буднего вечера или идею быстрого и вкусного обеда без лишних хлопот, вам повезло!",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/jinottogi-598x598.webp"),
    dopPhoto: require("./imgs/ramen/1000010487_detail_077.jpg"),
    name: "Суп Jin Ramen (Mild) Ottogi",
    price: "98грн",
    Defprice: "98грн",
    weight: "120г",
    type: "Суп",
    producer: "Ottogi",
    data: "Локшина Jin Ramen (Mild) от торговой марки Ottogi — это отличная возможность вкусно пообедать без лишних затрат времени и денег. Она обладает приятным вкусом средней остроты и хорошо утоляет голод, обеспечивая организм энергией. А насыщенный говяжий бульон с приятными грибными нотками не оставит вас равнодушными.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yumthaiboat-598x598.webp"),
    dopPhoto: require("./imgs/ramen/thaiboat-700x700.webp"),
    name: "Суп Thai Boat Noodles YumYum",
    price: "60грн",
    Defprice: "60грн",
    weight: "70г",
    type: 'Суп',
    producer: "YumYum",
    data: "“Човникова” лапша берет свое начало с XII-XV веков, когда в Таиланде лапшу подавали посетителям с лодок, находящихся на бортах каналов. С развитием туристической индустрии в Таиланде этот густой суп-лапша по-тайски постепенно стал частью тайского уличного питания.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/Tangle-Bulgogi-Alfredo-Tangluccine-Pack-108g-SamYang-1690875531161_512x512.webp"),
    dopPhoto: require("./imgs/ramen/samyangtanglebulgogialfredo1-700x700.webp"),
    name: "Лапша Samyang Bulgogi Alfredo Tangluccine",
    price: "148грн",
    Defprice: "148грн",
    weight: "102г",
    type: "Лапша",
    producer: "SamYang",
    data: "Tangle — это корейская паста, также известная как K-pasta, готовится из сушеной на воздухе лапши и фирменного корейского соуса. Паста фетучини со вкусом говядины Bulgogi в кремово-сырном соусе от Samyang — идеальный выбор для тех, кто ценит свое время и любит разнообразие в еде. Эта корейская лапша обладает ярким и насыщенным вкусом благодаря сочетанию ароматных специй и натуральных ингредиентов. Соус включает в себя нежное сочетание кремовых и сырных ноток, а также кусочки ароматной говядины, которые придают пасте неповторимый вкус.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/samyangrosecreamcup-598x598.webp"),
    name: 'Рамен Samyang Buldak "Rosé Cream" Маленький стакан',
    price: "98рн",
    Defprice: "98рн",
    weight: "80г",
    type: "Лапша рамен",
    producer: "SamYang",
    data: "Ощутите насыщенный вкус, не похожий ни на один другой, с почти сладким и кремовым вкусом K-Rosé соуса, который заставит вас хотеть еще больше. Идеальное сочетание любимого соуса пультак, острого перца и нежных сливок, которое определенно стоит попробовать. Благодаря уровню остроты 2 из 5 уровней BFL (Buldak Fire Level), этой лапшой могут наслаждаться даже те, кто предпочитает менее пикантные вкусы.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/samyangjjajangbigbowl-598x598.webp"),
    dopPhoto: require("./imgs/ramen/jjajangkoreanvers1-700x700.png"),
    name: "Лапша рамен Buldak Jjajang Samyang Big Bowl",
    price: "128грн",
    Defprice: "128грн",
    weight: "105г",
    type: "Лапша",
    producer: "SamYang",
    data: "Приготовленная из ингредиентов высшего качества, эта удивительная лапша заставит ваши вкусовые рецепторы трепетать от восторга! Этот вкусный корейский рамен — идеальная еда для любого случая, будь то быстрый и легкий обед или желание добавить пикантности ужину. Соблазнительное сочетание вкусов Buldak и Jjajang делает этот рамен по-настоящему уникальным. Buldak острый и пикантный, в то время как Jjajang из черных соевых бобов добавляет блюду нотки сладости, что делает эту лапшу неповторимой.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/jjajangkoreanvers-598x598.webp"),
    dopPhoto: require("./imgs/ramen/jjajangkoreanvers1-700x700.png"),
    name: "Лапша рамен Buldak Jjajang Samyang",
    price: "148грн",
    Defprice: "148грн",
    weight: "140г",
    type: "Лапша",
    producer: "SamYang",
    data: "Приготовленная из ингредиентов высшего качества, эта удивительная лапша заставит ваши вкусовые рецепторы трепетать от восторга! Этот вкусный корейский рамен — идеальная еда для любого случая, будь то быстрый и легкий обед или желание добавить пикантности ужину. Соблазнительное сочетание вкусов Buldak и Jjajang делает этот рамен по-настоящему уникальным. Buldak острый и пикантный, в то время как Jjajang из черных соевых бобов добавляет блюду нотки сладости, что делает эту лапшу неповторимой.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/nongansung-598x598.webp"),
    dopPhoto: require("./imgs/ramen/nongansung1-700x700.webp"),
    name: "Суп AnSungTangMyun Nongshim",
    price: "88грн",
    Defprice: "88грн",
    weight: "128г",
    type: 'Суп',
    producer: "Nongshim",
    data: "Идеальный баланс вкуса и пикантности, уникальная смесь специй, сочетание соевой пасты, высококачественной лапши и насыщенного бульона — всё это создаёт аутентичный вкус Южной Кореи. Наслаждайтесь дымным, острым вкусом, который делает это блюдо действительно особенным.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/3455.970.webp"),
    dopPhoto: require("./imgs/ramen/38668e1cb63e357b757ec9574adf9477.jpg"),
    name: "Острый Рамен Chapaguri в миске Nongshim",
    price: "124грн",
    Defprice: "124грн",
    weight: "114г",
    type: "Лапша",
    producer: "Nongshim",
    data: "Лапша Nongshim Chapaguri это хороший выбор для любителей остроты и морепродуктов. Рамен приготовлен из высококачественных продуктов, которые не только вкусные и сотавляют приятные впечатления, но и сохранят ваше здоровье.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/chapagettinongshim-598x598.webp"),
    dopPhoto: require("./imgs/ramen/chapagettinongshim1-700x700.webp"),
    name: "Лапша рамен Chapagetti Nongshim",
    price: "90грн",
    Defprice: "90грн",
    weight: "140г",
    type: 'Лапша',
    producer: "Nongshim",
    data: "Компания Nongshim создала Chapagetti, чтобы корейцы могли легче наслаждаться любимым чачжанмёном дома. Производители улучшили вкус, добавив в соус чачжан жареный лук и премиум оливковое масло, которые мягко подчеркивают вкус.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/nongshimangryneoguri-598x598.webp"),
    dopPhoto: require("./imgs/ramen/nongshimangryneoguri1-700x700.webp"),
    name: "Суп Angry Neoguri Udon Nongshim",
    price: "84рн",
    Defprice: "84рн",
    weight: "120г",
    type: 'Суп',
    producer: "Nongshim",
    data: "Жевательная лапша удон, насыщенный бульон из морепродуктов и смесь острых приправ — это взрыв вкусов, который заставит вас захотеть ещё. В упаковке находятся лапша, суповая основа, кусочек ламинарии и пакетик с хлопьями в форме енотика.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/udonneoguri-598x598.webp"),
    dopPhoto: require("./imgs/ramen/udonneoguri1-700x700.webp"),
    name: "Суп Udon Neoguri Nongshim",
    price: "84грн",
    Defprice: "84грн",
    weight: "120г",
    type: 'Суп',
    producer: "Nongshim",
    data: "Суп удон с морепродуктами обладает насыщенным пикантным вкусом по-корейски. Лапша, содержащая порошковый бульон с насыщенным вкусом, мягкая и густая, как настоящая корейская лапша, которой можно наслаждаться в Украине, не отправляясь в Корею.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/samyangmaptaengblackpepperbeefbowl-598x598.webp"),
    dopPhoto: require("./imgs/ramen//youjinmom2_30603469_192838181507154_3783325352609185792_n-1024x1024.jpg"),
    name: 'Суп Maptaeng Samyang "Черный перец и говядина"',
    price: "138грн",
    Defprice: "138грн",
    weight: "110г",
    type: 'Суп',
    producer: "SamYang",
    data: "Пикантный и освежающе пряный рамен с говядиной и черным перцем Samyang Maeptaeng готовят из бульона с различными овощами, к которому добавляют зеленый лук, перец чили и чеснок, чтобы подчеркнуть глубокий вкус умами. Насыщенный говяжий бульон с добавлением черного перца имеет освежающий пикантный вкус и пряный аромат.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/samyangmaptaenggarlicclambowl-598x598.webp"),
    dopPhoto: require("./imgs/ramen/samyangmaptaenggarlicclam1-700x700.webp"),
    name: 'Суп Maptaeng Samyang "Острый чеснок и морепродукты"',
    price: "138грн",
    Defprice: "138грн",
    weight: "110г",
    type: 'Суп',
    producer: "SamYang",
    data: "Пикантный и освежающе острый рамен с моллюсками и чесноком Samyang Maeptaeng готовят из бульона с различными овощами, к которому добавляют зеленый лук, перец чили, чеснок и имбирь, чтобы подчеркнуть глубокий вкус умами. Насыщенный бульон с моллюсками, с добавлением креветок и кальмаров имеет освежающий пикантный вкус и аромат чеснока.",
    shelfLife: "6 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/tomyumkungnew-598x598.webp"),
    dopPhoto: require("./imgs/ramen/tomyumkong-700x700.webp"),
    name: 'Суп Jumbo Tom Yum Kung YumYum',
    price: "60грн",
    Defprice: "60грн",
    weight: "63г",
    type: 'Суп',
    producer: "SamYang",
    data: "Попробуйте изысканное сочетание качественной упругой лапши и аутентичных тайских специй с Jumbo Tom Yum Kung от YumYum. Изготовленный из отборных ингредиентов, он сохраняет весь вкус традиционного супа том ям в удобном одноразовом формате. Рецепт также включает сушеные креветки, лемонграсс, листья кафрского лайма, галангал и чили, чтобы вы могли насладиться экзотическим и аутентичным вкусом супа Том Ям Кунг.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yumyumlobsternew-598x598.webp"),
    name: 'Лапша Spicy Lobster Flavour YumYum',
    price: "72грн",
    Defprice: "72грн",
    weight: "75г",
    type: 'Лапша',
    producer: "YumYum",
    data: "Премиум лапша быстрого приготовления YumYum со вкусом омара. Сочетание качественной и мягкой лапши с насыщенным тайским соусом из морепродуктов, приготовленным из лучших ингредиентов, устанавливает новый стандарт острого быстрого приготовления лапши.",
    shelfLife: "1 год",
  },
];

export const tokkpokiInformation = [
  {
    text: "Токпокки — это популярное корейское блюдо, представляющее собой жаренные или тушеные рисовые палочки, обычно в пряном соусе. Мы предлагаем такие бренды, как: Samyang и Yopokki,",
    img: require("./imgs/icons/OIP.jpg"),
  },
];
export const tokkpoki = [
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/carbotopokki-598x598.webp"),
    dopPhoto: require("./imgs/ramen/carbotopokki1-700x700.webp"),
    name: "Токпоки Samyang Buldak Carbonara",
    price: "236грн",
    Defprice: "236грн",
    weight: "179г",
    type: "Токпокки",
    producer: "SamYang",
    data: "Buldak Carbonara Topokki – это вкусное, пикантное острое блюдо с выразительным итальянским акцентом, которое можно приготовить в микроволновке. Большая порция рисовых токпокки в кремовом соусе - уникальное предложение для обеда или ужина, которое можно приготовить всего за 3 минуты. Секрет их фантастического вкуса заключается в сочетании ароматного сыра и тщательно подобранной смеси специй, таких как чеснок, лук, перец и паприка.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/carbotopokki-598x598.webp"),
    dopPhoto: require("./imgs/ramen/carbotopokki1-700x700.webp"),
    name: "Токпоки Samyang Buldak Carbonara",
    price: "236грн",
    Defprice: "236грн",
    weight: "179г",
    type: "Токпокки",
    producer: "SamYang",
    data: "Buldak Carbonara Topokki – это вкусное, пикантное острое блюдо с выразительным итальянским акцентом, которое можно приготовить в микроволновке. Большая порция рисовых токпокки в кремовом соусе - уникальное предложение для обеда или ужина, которое можно приготовить всего за 3 минуты. Секрет их фантастического вкуса заключается в сочетании ароматного сыра и тщательно подобранной смеси специй, таких как чеснок, лук, перец и паприка.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yopokkicheese-598x598.webp"),
    dopPhoto: require("./imgs/ramen/Yopokki-Tteokbokki-Cheese-Cup-EU-1080-5.webp"),
    name: "Сырные Токпокки Yopokki",
    price: "160грн",
    Defprice: "160грн",
    weight: "120г",
    producer: "Yopokki",
    data: "Острый и пикантный сырный соус безупречно дополняет рисовые палочки, превращая каждую порцию в настоящее удовольствие. Позиция предназначена для приготовления в микроволновой печи - блюдо готовится всего за несколько минут, так что вы можете наслаждаться настоящей корейской кухней в уюте собственного дома.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yopokkigarlicteriyaki-598x598.webp"),
    dopPhoto: require("./imgs/ramen/yopokkigarlicteriyaki1-700x700.webp"),
    name: "Чесночные Токпокки Yopokki",
    price: "160грн",
    Defprice: "160грн",
    weight: "120г",
    producer: "Yopokki",
    data: "Аппетитное сочетание ароматного чеснока и сладко-острого соуса терияки, которое добавляет уникальный оттенок классическим токпокки. Позиция предназначена для приготовления в микроволновой печи - блюдо готовится всего за несколько минут, так что вы можете наслаждаться настоящей корейской кухней в уюте собственного дома.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yopokkihalalspicy-598x598.webp"),
    dopPhoto: require("./imgs/ramen/yopokkihalalspicy1-700x700.webp"),
    name: "Острые Токпокки Yopokki",
    price: "162рн",
    Defprice: "162рн",
    weight: "140г",
    type: "Токпокки",
    producer: "Yopokki",
    data: "Клейкие палочки и соблазнительный сладко-острый соус на основе перцовой пасты кочудян создают райское сочетание, которое надолго останется в вашей памяти. Позиция предназначена для приготовления в микроволновой печи - блюдо готовится всего за несколько минут, так что вы можете наслаждаться настоящей корейской кухней в уюте собственного дома.",
    shelfLife: "1 год",
  },

  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yopokkisweetspicy-598x598.webp"),
    dopPhoto: require("./imgs/ramen/dukboki.png"),
    name: "Сладко-острые Токпокки Yopokki",
    price: "160грн",
    Defprice: "160грн",
    weight: "120г",
    type: "Токпокки",
    producer: "Yopokki",
    data: "Sweet & Spicy Yopokki имеют идеальный уровень остроты 2/5, что делает это блюдо универсальным вариантом, который подойдет как любителям пряного, так и тем, кто предпочитает менее острое. Готовится лакомство всего за несколько минут, так что вы можете наслаждаться настоящей корейской кухней в уюте собственного дома.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/tteokbokkibuldak-598x598.webp"),
    dopPhoto: require("./imgs/ramen/tteokbokkibuldak11-700x700.webp"),
    name: 'Токпокки Buldak Samyang "Острая курица"',
    price: "245грн",
    Defprice: "245грн",
    weight: "185г",
    type: "Токпокки",
    producer: "SamYang",
    data: "Булдак Токпокки — рисовые ттокпокки с известным острым соусом Булдак со вкусом острой курицы. Сочетание жгучего перца чили, ароматной пасты кочудян, соевого соуса, сахара и ароматных специй, таких как карри, чеснок и лук, создаёт захватывающую палитру вкусов, перед которой не сможет устоять ни один поклонник корейских деликатесов.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yopokkikimchi-598x598.webp"),
    dopPhoto: require("./imgs/ramen/yopokkikimchi1-700x700.webp"),
    name: "Токпокки Kimchi Yopokki",
    price: "151грн",
    Defprice: "151грн",
    weight: "115г",
    type: "Токпокки",
    producer: "Yopokki",
    data: "Kimchi Sauce Yopokki — острая корейская уличная еда, упакованная в удобную чашку. Клейкие палочки ток и соблазнительно ароматный, сладко-остро-кисловатый соус с кимчи создают божественное сочетание, которое надолго останется в вашей памяти.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/sempiosweetspicy-598x598.webp"),
    name: "Токпокки Sweet & Spicy Sempio",
    price: "180грн",
    Defprice: "180грн",
    weight: "160г",
    type: "Токпокки",
    data: "Kimchi Sauce Yopokki — острая корейская уличная еда, упакованная в удобную чашку. Клейкие палочки ток и соблазнительно ароматный, сладко-остро-кисловатый соус с кимчи создают божественное сочетание, которое надолго останется в вашей памяти.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/ramen/yopokkijjajang-598x598.webp"),
    dopPhoto: require("./imgs/ramen/yopokkijjajang1-700x700.webp"),
    name: "Токпокки Jjajang Yopokki",
    price: "160грн",
    Defprice: "160грн",
    weight: "120г",
    type: "Токпокки",
    producer: "Yopokki",
    data: "Токпоккі Jjajang - рисовые палочки, покрытые вкусным, ароматным соусом чачжан, очень популярны как среди корейцев, так и во всем мире. Нежный, сладко-соленый соус чачжан из черных соевых бобов придает токпоккі оттенок сладости.",
    shelfLife: "1 год",
  },
];

export const allNoodles = [...noodles, ...tokkpoki];

export const soucesInformation = [
  {
    text: "Азиатские соусы занимают важное место в кулинарии различных стран Азии. Они отличаются разнообразием вкусов, текстур и применений. Некоторые блюда, такие как лапша удон или соба, просто невозможно представить без любимого острого соуса. Купив наши соусы вы сможете ощутить прелесть азиатской кухни у себя дома",
    img: require("./imgs/icons/photo_2024-08-04_21-07-54-removebg-preview.png"),
  },
];
export const allSauces = [
  ...recomendedSauces,
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/buldakmayotut-598x598.webp"),
    dopPhoto: require("./imgs/sauces/buldakmayo-700x700.webp"),
    name: "Острый майонез Samyang Buldak",
    price: "280грн",
    Defprice: "280грн",
    weight: "250г",
    producer: "SamYang",
    data: "Остро-пикантный майонез со вкусом любимого соуса buldak непременно дополнит любое ваше любимое блюдо. Этот продукт определённо стоит попробовать тем, кто ищет новый вкусный и пикантный соус. Отлично сочетается с белым рисом, лапшой, а также прекрасно подходит в качестве заправки для салатов.",
    shelfLife: "10 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/sauceshiitake1-598x598.webp"),
    dopPhoto: require("./imgs/sauces/sauceshiitake2-700x700.webp"),
    name: "Грибной соус Shiitake Zhongjing",
    price: "20грн",
    Defprice: "20грн",
    weight: "16г",
    data: "Грибы шиитаке — это здоровая еда с высоким содержанием белков и низким содержанием жира. Частое употребление грибов шиитаке полезно для сбалансирования диеты и поддержания физической жизненной силы. Соус отлично сочетается с жареным и паровым рисом, лапшой, булочками.",
    shelfLife: "18 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/2xspicysauce11-598x598.webp"),
    dopPhoto: require("./imgs/sauces/samyyangChili.png"),
    name: "Острый соуc Buldak 2x Spicy Samyang",
    price: "278грн",
    Defprice: "278грн",
    weight: "200г",
    producer: "SamYang",
    data: "Острый соус Samyang Buldak 2x Spicy — это пикантный соус, который станет изысканным завершающим штрихом к вашим любимым блюдам, будь то мясо на гриле, обжаренные овощи или лапша быстрого приготовления.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/buldaksaucestick-598x598.webp"),
    name: "Соуc Buldak Hot Sauce Samyang (16г)",
    price: "33грн",
    Defprice: "33грн",
    weight: "16г",
    producer: "SamYang",
    data: "Классический соус Бульдак с соблазнительными сладкими нотками и восхитительным вкусом острой корейской курицы. Благодаря универсальному размеру, его удобно брать в походы или даже на работу, что бы украсить свой робочий день.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/zhongjingbeefsauce-598x598.webp"),
    dopPhoto: require("./imgs/sauces/zhongjingbeefsauce1-700x700.webp"),
    name: "Пряний соус с говядиной Zhongjing",
    price: "22грн",
    Defprice: "22грн",
    weight: "16г",
    data: "Соус с говядиной и грибами шиитаке в удобной порционной упаковке от известного китайского бренда Zhongjing. Сочетание десяти специй и высококачественной говядины создает насыщенный аутентичный вкус. Отлично сочетается с булочками бао, паровым рисом или лапшой.",
    shelfLife: "18 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/daikonwujiang-598x598.webp"),
    dopPhoto: require("./imgs/sauces/daikon.jpg"),
    name: "Маринованый дайкон Wujiang",
    price: "24грн",
    Defprice: "24грн",
    weight: "22г",
    data: "Хрустящие кусочки маринованного дайкона прекрасно подойдут к блюдам из риса и лапши. Также его можно использовать в качестве начинки для паровых булочек или подавать как гарнир; нарезанная редька способна обогатить вкус жареного мяса или рагу. Дайкон Wujiang, нарезанный кубиками, изготавливается из крупной редьки, выращенной на северо-востоке.",
    shelfLife: "16 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/saucebuldakhot-598x598.webp"),
    dopPhoto: require("./imgs/sauces/buldaksauce1-700x700.jpg"),
    name: "Соуc Buldak Hot Sauce Samyang",
    price: "268грн",
    Defprice: "268грн",
    weight: "200г",
    producer: "SamYang",
    data: "Традиционный соус Бульдак, сочетающий соблазнительную сладость и насыщенный вкус острой корейской курицы, — идеальный выбор для вас! Этот пикантный соус прекрасно дополнит ваши любимые блюда, будь то гриль, жареные овощи или лапша быстрого приготовления.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/hubangmushroomnew-598x598.webp"),
    dopPhoto: require("./imgs/sauces/hubangmushroomnew2-700x700.webp"),
    name: "Острый соус с шиитаке и побегами бамбука Tiger Bang",
    price: "278грн",
    Defprice: "278грн",
    weight: "200г",
    data: "Острый соус с шиитаке и кусочками молодых побегов бамбука. Этот соус можно использовать в качестве приправы, заправки для салатов, холодных блюд, а также добавлять к лапше и жареному рису.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sauces/leekumkeeoystersauce510ml-598x598.webp"),
    name: "Устричный соус Lee Kum Kee Oyster Sauce",
    price: "290грн",
    Defprice: "290грн",
    weight: "510г",
    data: "Устричный соус — важный компонент для поклонников азиатской кухни. Этот качественный соус придаёт любому блюду насыщенный аромат и глубокую пикантность. Мягкий устричный соус от Lee Kum Kee отлично подходит для приготовления жареных овощей, мяса и рыбы, а также в качестве маринада. У соуса лёгкий рыбный вкус с приятной сладостью и оттенком морской соли.",
    shelfLife: "3 года",
  },
];

export const sweetsInformation = [
  {
    text: "Азиатские сладости удивляют разнообразием вкусов, текстур и оригинальностью. Каждая страна региона имеет свои уникальные десерты, которые могут быть совершенно непривычны для западного вкуса, но несомненно заслуживают внимания. В нашем магазине есть моти, батончики, пирожные и различные конфеты.",
    img: require("./imgs/icons/photo_2024-08-04_21-13-43-removebg-preview.png"),
  },
];

export const allSweets = [
  ...recomendedSweets,
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/0e1f8fec-4da1-4f08-8cab-6ee234f46489.d807aa6f774d7db1d202d6a8e4379c05.png"),
    dopPhoto: require("./imgs/sweets/mochipeanutyukilove1-700x700.webp"),
    name: "Moти Peanut Mochi Yuki & Love",
    price: "175грн",
    Defprice: "175грн",
    weight: "210г",
    data: "Нежный десерт из клейкого рисового теста с начинкой из арахисовой пасты и ореховым ароматом. Дайфуку мочи прекрасно подходит в качестве сладкого угощения к чашке любимого кофе или чая. В упаковке 6 пирожных, каждое в отдельном бумажном стаканчике.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/mochitaroyukilovenew-598x598.webp"),
    dopPhoto: require("./imgs/sweets/mochitaroyukilove1-700x700.webp"),
    name: "Moти Taro Mochi Yuki & Love",
    price: "175грн",
    Defprice: "175грн",
    weight: "210г",
    data: "Нежный десерт из клейкого рисового теста с начинкой из таро и сладким ореховым вкусом. Дайфуку моти станет отличным дополнением к вашей любимой чашке кофе или чаю. В упаковке 6 пирожных в бумажных стаканчиках.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/bibizanmarshmallowstrawberry-598x598.webp"),
    dopPhoto: require("./imgs/sweets/bibizanmarshmallowstrawberry1-700x700.webp"),
    name: "Маршмелоу Chocolate Marshmallow Strawberry Bibizan",
    price: "145грн",
    Defprice: "145грн",
    weight: "200г",
    producer: "Bibizan",
    data: "Вкуснейший десерт с воздушной кремово-клубничной начинкой, покрытый белым шоколадом, не оставит вас равнодушным. Идеальное сочетание текстуры и вкуса подарит вам незабываемые ощущения.",
    shelfLife: "9 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/orionmygummyplum-598x598.webp"),
    dopPhoto: require("./imgs/sweets/orionmygummyplum2-700x700.webp"),
    name: "Желейные конфеты со вкусом сливы Orion",
    price: "60грн",
    Defprice: "60грн",
    weight: "36г",
    producer: "Orion",
    data: "Жевательные конфетки My Gummy Plum от Orion, выполненные в форме маленьких фруктов, сделаны из натуральных компонентов, что делает их не только вкусными, но и полезными. Богатый вкус сливы обязательно порадует ваши вкусовые рецепторы.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/fruitYazik.jpg"),
    dopPhoto: require("./imgs/sweets/fruitLenta.jpg"),
    name: "Фруктовые язычки Чупа Чупс",
    price: "12грн",
    Defprice: "12грн",
    weight: "10г",
    data: "Многоцветные фруктовые ленты с насыщенным кислым и сладким вкусом, которые нравятся и детям, и взрослым. Каждая конфета упакована в удобную индивидуальную упаковку.",
    shelfLife: "18 месяцев",
  },

  {
    id: uuidv4(),
    photo: require("./imgs/sweets/44-1000x1000.jpg"),
    dopPhoto: require("./imgs/sweets/franzziyogurtchoco1-700x700.webp"),
    name: "Печенье Franzzi Yogurt Chocole",
    price: "55грн",
    Defprice: "55грн",
    weight: "200г",
    data: "Вкуснейший десерт с воздушной кремово-клубничной начинкой, покрытый белым шоколадом, не оставит вас равнодушным. Идеальное сочетание текстуры и вкуса подарит вам незабываемые ощущения.",
    shelfLife: "9 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/franzzidarkchocolate-598x598.webp"),
    dopPhoto: require("./imgs/sweets/franzzidarkchocolate1-700x700.webp"),
    name: "Печенье Franzzi Dark Chocolate",
    price: "55грн",
    Defprice: "55грн",
    weight: "58г",
    data: "Нежное песочное печенье с начинкой из шоколадного крема и изысканным вкусом. Каждое печенье упаковано отдельно.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/297dbbca23384d31bdcd9f09efdb1862.jpg"),
    dopPhoto: require("./imgs/sweets/franzzivanillalemon1-700x700.webp"),
    name: "Печенье Franzzi Vanilla Lemon Chocolate",
    price: "55грн",
    Defprice: "55грн",
    weight: "58г",
    data: "Мягкое песочное печенье с кремовой начинкой и утонченным вкусом ванили и лимона. Каждое печенье упаковано отдельно.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/jellyCandyYouka.jpg"),
    dopPhoto: require("./imgs/sweets/OIP (1).jpg"),
    name: "Фруктовые конфеты Youka Jelly",
    price: "18грн",
    Defprice: "18грн",
    weight: "60г",
    data: "Разноцветные червячки с разными фруктовыми вкусами. Мягкие и таят во рту, имеют приятный запах который подбордит Вас.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/e2e8c4be-8204-4737-9346-af5dbdaa2fd4.jpg"),
    name: "Шоколадный батончик Haitai с кусочками миндаля",
    price: "65грн",
    Defprice: "65грн",
    weight: "55г",
    data: "Шоколадный батончик Haitai с миндальными кусочками — это восхитительное лакомство, которое сочетает в себе насыщенный шоколадный вкус и хрустящие миндальные вкрапления. Каждый кусочек батончика дарит не только удовольствие от сладкого, но и дополнительную текстуру благодаря орехам. Идеально подходит для перекуса или сладкого удовольствия в любое время дня.",
    shelfLife: "9 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/OIP (2).jpg"),
    name: "Шоколадный батончик Haitai с ореховой пастой",
    price: "65грн",
    Defprice: "65грн",
    weight: "55г",
    data: "Шоколадный батончик Haitai с ореховой пастой — это изысканное сочетание нежного молочного шоколада и гладкой ореховой пасты. Каждое лакомство предлагает насыщенный вкус и кремовую текстуру, которая идеально гармонирует с шоколадной оболочкой. Отличный выбор для любителей сладких угощений и ореховых десертов.",
    shelfLife: "9 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/101840071.jpg"),
    name: "Шоколадный батончик Haitai с соленной карамелью",
    price: "65грн",
    Defprice: "65грн",
    weight: "55г",
    data: "Шоколадный батончик Haitai с соленой карамелью сочетает в себе насыщенный вкус гладкого шоколада и сладко-соленую карамель. Этот батончик идеально подходит для тех, кто ценит гармонию вкусов и наслаждается уникальным сочетанием сладости и легкой солености.",
    shelfLife: "9 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/bibizanchestnut-598x598.webp"),
    dopPhoto: require("./imgs/sweets/honeyDesert.webp"),
    name: "Mедовые каштаны Bibizan",
    price: "80грн",
    Defprice: "80грн",
    weight: "60г",
    producer: "Bibizan",
    data: "Каштаны, вырастившиеся в горах Яньшань, после зрелости собираются вручную и тщательно отбираются. Эти медовые каштаны Bibizan, с низким содержанием жира и высоким уровнем питательных веществ, станут отличной закуской для тех, кто ценит новые вкусы.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/franzzimatcha-598x598.webp"),
    dopPhoto: require("./imgs/sweets/matcha.jpg"),
    name: "Печенье Franzzi Matcha Chocolate",
    price: "55грн",
    Defprice: "55грн",
    weight: "58г",
    data: "Мягкое песочное печенье с шоколадной начинкой и утонченным ароматом зелёного чая. Каждое печенье упаковано в отдельную упаковку.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/custardpieorion-598x598.webp"),
    dopPhoto: require("./imgs/sweets/custardpieorion1-700x700.webp"),
    name: "Пирожные с заварным кремом Orion",
    price: "158грн",
    Defprice: "158грн",
    weight: "138г",
    producer: "Orion",
    data: "Любимые пирожные Orion с насыщенной начинкой из заварного крема. Эти пирожные обладают невероятной мягкостью и вкусом. Они станут отличным дополнением к чашечке горячего чая или кофе.",
    shelfLife: "8 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/tiramisuorion-598x598.webp"),
    dopPhoto: require("./imgs/sweets/tiramisuorion1-700x700.webp"),
    name: "Пирожные с терамису Orion",
    price: "158грн",
    Defprice: "158грн",
    weight: "138г",
    producer: "Orion",
    data: "Комбинация изысканного тирамису-бисквита с мягким заварным кремом из яичных желтков и сахара. Отлично сочетается с кофе или молоком. В каждой упаковке находится 12 пирожных по 23 г каждое, каждое в индивидуальной упаковке.",
    shelfLife: "8 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/3a114fa3-fcd7-479b-949e-150df96d8d62.jpg"),
    dopPhoto: require("./imgs/sweets/orionmygummygrape1-700x700.webp"),
    name: "Желейные конфеты со вкусом винограда Orion",
    price: "66грн",
    Defprice: "66грн",
    weight: "43г",
    producer: "Orion",
    data: "Желейные конфеты My Gummy Grape от Orion в виде маленьких фруктов содержат 60% натурального виноградного сока. Эти сладости обладают ярким виноградным вкусом и понравятся как детям, так и взрослым.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/orionmygummylychee-598x598.webp"),
    dopPhoto: require("./imgs/sweets/OIP (3).jpg"),
    name: "Желейные конфеты со вкусом личи Orion",
    price: "66грн",
    Defprice: "66грн",
    weight: "36г",
    producer: "Orion",
    data: "Желейные конфеты My Gummy Lychee от Orion выполнены в форме маленьких фруктов. Их свежий вкус и сочная текстура желе напоминают настоящий личи, поэтому эти сладости будут по душе как детям, так и взрослым.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/blob.jpg"),
    dopPhoto: require("./imgs/sweets/bibizanmango1-700x700.webp"),
    name: " Желейные конфеты со вкусом манго Bibizan",
    price: "79грн",
    Defprice: "79грн",
    weight: "85г",
    producer: "Bibizan",
    data: "Липкие конфетки со вкусом манго и фруктового сока. Они обладают мягкой текстурой, кисло-сладким вкусом и неповторимым ароматом свежего манго, который не оставит вас равнодушными.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/fe87eb2104c480cf95e8cc3013688c3c.jpg"),
    dopPhoto: require("./imgs/sweets/OIP (6).jpg"),
    name: "3D зефир в виде утят HoleyWood",
    price: "76грн",
    Defprice: "76грн",
    weight: "40г",
    data: "Очень мягкий и сладкий маршмеллоу в виде маленьких утят. Каждое утенок-мармелад – это настоящий шедевр для сладких наслаждений. Они обладают воздушной текстурой и нежным ароматным вкусом, который тает во рту. Эти очаровательные маршмеллоу отлично подойдут для украшения тортов, кексов, печений или как самостоятельное угощение.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/sweets/20231005205814724.png"),
    dopPhoto: require("./imgs/sweets/OIP (7).jpg"),
    name: "Карамельный пудинг с клейкими рисовыми шариками Pudding Dog от Sanrio",
    price: "159грн",
    Defprice: "159грн",
    data: "Карамельный пудинг с клейкими рисовыми шариками Pudding Dog от Sanrio — это изысканный десерт, сочетающий в себе сладость карамели и текстуру клейкого риса. Этот уникальный пудинг обладает кремовой консистенцией и насыщенным карамельным вкусом, который приятно тает во рту.",
    shelfLife: "9 месяцев",
  },
];

export const chipsInformation = [
  {
    text: "Азиатские чипсы и снеки — это целый мир уникальных вкусов и текстур, который отличается от привычных западных аналогов. В Азии снеки не просто закуска, а часть культуры, отражающая разнообразие и богатство местных кулинарных традиций.",
    img: require("./imgs/icons/istockphoto.png"),
  },
];

export const allChips = [
  ...recomendedChips,
  {
    id: uuidv4(),
    photo: require("./imgs/chips/ottogippushusnack-598x598.webp"),
    dopPhoto: require("./imgs/chips/ottogippushusnack1-700x700.webp"),
    name: "Снеки Ottogi Ppushu Ppushu Noodle Snack",
    price: "98грн",
    Defprice: "98грн",
    type: "Снеки",
    weight: "90г",
    producer: "Ottogi",
    data: "Рамен-снек от известного бренда Ottogi. Очень острый и хрустящий. Вам не нужно кипятить воду, чтобы насладиться любимым вкусом, так как эту лапшу можно есть прямо из пакетика, предварительно раздробив её и посыпав приправой. Снеки идеально подходят для перекусов в пути, вечеринок или просто для того, чтобы утолить желание острого в любое время.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/nongshimgochujangcrackers-598x598.webp"),
    dopPhoto: require("./imgs/chips/nongshimgochujangcrackers1-700x700.webp"),
    name: "Острые снеки Nongshim Gochujang Flavor Shrimp Crackers",
    price: "138грн",
    Defprice: "138грн",
    type: "Снеки",
    weight: "95г",
    producer: "Nongshim",
    data: "Острые снеки от бренда Nongshim станут отличным выбором для любителей острого. Пикантная и очень хрустящая закуска со вкусом креветок и корейской острой пасты кочуджан от бренда Nongshim определенно оставит незабываемые впечатления. Яркий вкус молотых креветок и приятная острота делают эти снеки идеальной закуской для любого случая.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/hbafspicyalmond-598x598.webp"),
    dopPhoto: require("./imgs/chips/hbafspicyalmond1-700x700.webp"),
    name: "Острый миндаль со вкусом курицы HBAF",
    price: "92грн",
    Defprice: "92грн",
    type: "Закуски",
    weight: "32г",
    data: "Вкусная пикантность и потрясающий аромат острых орехов с привкусом курицы от знаменитого корейского бренда HBAF. Орехи известны своим высоким содержанием белка, полезных жиров, клетчатки, а также важных витаминов и минералов, что обеспечивает заряд энергии на целый день.",
    shelfLife: "1 год",
  },

  {
    id: uuidv4(),
    photo: require("./imgs/chips/beierxiangoctopuspork-598x598.webp"),
    dopPhoto: require("./imgs/chips/beierxiangoctopus1-700x700.webp"),
    name: "Острые снеки Beierxiang Spicy Octopus",
    price: "54грн",
    Defprice: "54грн",
    type: "Снеки",
    weight: "46г",
    data: "Пикантная и хрустящая закуска из щупалец осьминога, запечённых на гриле с ароматом тайских специй и лёгкой сладковатой ноткой. Идеально подходит для сопровождения вашего любимого напитка или как изысканное угощение на вечеринке.",
    shelfLife: "9 месяцев",
  },

  {
    id: uuidv4(),
    photo: require("./imgs/chips/zzaldduk-598x598.webp"),
    dopPhoto: require("./imgs/chips/61Rg0dUi+pL.jpg"),
    name: "Снеки Zzaldduk Samyang",
    price: "148грн",
    Defprice: "148грн",
    type: "Снеки",
    weight: "120г",
    producer: "SamYang",
    data: "Пикантная и невероятно хрустящая корейская закуска Zzaldduk от Samyang доставляет гастрономическое удовольствие, сочетая вкус остро-сладкого куриного рамена с непревзойденной хрустящей текстурой.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/zzaldduk2xspicy-598x598.webp"),
    dopPhoto: require("./imgs/chips/OIP (1).jpg"),
    name: "Снеки Zzaldduk 2x Spicy Samyang",
    price: "148грн",
    Defprice: "148грн",
    type: "Снеки",
    weight: "80г",
    producer: "SamYang",
    data: "Чипсы, обсыпанные аппетитной смесью из красного перца кочукару и жгучего перца хабанеро, с добавлением пасты кочудян и соевого соуса. Они обладают сладковатым вкусом и удивительной хрусткостью.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/orionkimchichips-598x598.webp"),
    dopPhoto: require("./imgs/chips/chipKimchi.jpg"),
    name: "Чипсы Korean Kimchi Flavor Orion",
    price: "98грн",
    Defprice: "98грн",
    type: "Чипсы",
    weight: "70г",
    data: "Рамен-снек от известного бренда Ottogi. Очень острый и хрустящий. Вам не нужно кипятить воду, чтобы насладиться любимым вкусом, так как эту лапшу можно есть прямо из пакетика, предварительно раздробив её и посыпав приправой. Снеки идеально подходят для перекусов в пути, вечеринок или просто для того, чтобы утолить желание острого в любое время.",
    shelfLife: "9 месяцев",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/nongshrimpchips-598x598.webp"),
    name: "Чипсы Nongshim со вкусом креветок",
    price: "148грн",
    Defprice: "148грн",
    type: "Чипсы",
    weight: "75г",
    producer: "Nongshim",
    data: "Рамен-снек от известного бренда Ottogi. Очень острый и хрустящий. Вам не нужно кипятить воду, чтобы насладиться любимым вкусом, так как эту лапшу можно есть прямо из пакетика, предварительно раздробив её и посыпав приправой. Снеки идеально подходят для перекусов в пути, вечеринок или просто для того, чтобы утолить желание острого в любое время.",
    shelfLife: "1 год",
  },
  {
    id: uuidv4(),
    photo: require("./imgs/chips/yembuldak2xspicysnack-598x598.webp"),
    dopPhoto: require("./imgs/chips/yembuldak2xspicysnack-DopPhoto.webp"),
    name: "Снеки Buldak Tteokbokki 2x Spicy Yem",
    price: "128грн",
    Defprice: "128грн",
    type: "Снеки",
    weight: "100г",
    data: "Хрустящие снеки Yem с ярким сладко-острым вкусом теперь стали в два раза острее, и по-прежнему сохраняют такой же потрясающий вкус и высокое качество, как культовые снеки Zzaldduk от Samyang.",
    shelfLife: "1 год",
  },
];
